apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearing
  labels:
    app: elearning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elearning
  template:
    metadata:
      labels:
        app: elearning
    spec:
      containers:
      - name: elearning
        image: vivekbhatti597/elearning:latest  # Replace with your Docker image
        ports:
        - containerPort: 3700  # Replace with the port your app runs on
